### ISSUE TITLE
Biome generation doesn't work with build 3002 on 1.19.3

### ISSUE THREAD

**Issue by DaJMaN4** [IrisDimensions/overworld#310] opened 2023-05-17 20:04 UTC
### Describe the problem

While initialization pack I got this.
[18:52:19 INFO]: [Iris]: The Pack overworld is INCAPABLE of generating custom biomes

When creating iris world biomes do generate normally but after standard server restart (stop command and then start)
New chunks generate with only minecraft:plains biome. 
Chunks previously generated remains with original biome. 

I sent fraction of log, the rest seems to look normally.

### What Should Happen

The biomes should generate. 

### What Biome

All

### Minecraft Version

1.19.3

### Iris Version

2.4.3 

### Relevant log output. (IF APPLICABLE)

https://mclo.gs/Xwwgjyq

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by svdgoor** [comment] 2023-05-17 20:10
https://mclo.gs/Xwwgjyq#L124
see line 124 up to 126 of your log.
The warning is intended behaviour, and your server will shutdown after.
You can then manually turn the server back on, after which custom biomes should start generating again as usual.

**Comment by svdgoor** [comment] 2023-05-17 20:11
Furthermore this is an issue which you would generally put on the [Iris repository](https://github.com/VolmitSoftware/Iris/Issues)

**Comment by DaJMaN4** [comment] 2023-05-18 21:25
I see, that message has nothing to do in this issue. But I think there is something wrong with the generator. 

After manually starting the server biomes do generate normally, but after next restart they don't. Around the biomes that generated at the first time there are just plains, look at the photo.  
![image](https://github.com/IrisDimensions/overworld/assets/87906470/b6c9e3f0-994e-4af5-a2f8-97eea0aaf50a)
I also started a new server with just Iris installed and checked if this will continue and it does. I am sending full log of this server run. 
The only concerning thing that I find is a purpur thread dump creating because of overloading the server. That appeared while creating the world, this is the first time it appeared to me while running Iris.
https://mclo.gs/rG7XyPX

**Comment by NextdoorPsycho** [comment] 2023-05-20 20:02
Well any issues in 1.19.3 were fixed on 1.19.4. Furthermore im not certain if the Datapack transfers work like that. Can you Stop the server, delete all iris worlds, clean it from the bukkit yml, delete the plugin folder. and start from there on a new up to date server?  if the problem persists, and you let the server restart once BEFORE doing anything, and you are manually issuing the command to create a world (/iris create) please reach out in the discord!

**Comment by NextdoorPsycho** [comment] 2023-05-20 20:03
But im closing this as an issue here as it does infact if anywhere belong with the plugin as coco mentioned, but also because id like to ensure you get help. so please reach out on the discord if that does not work!

**Closed as completed by NextdoorPsycho** 2023-05-20 20:03 UTC

**Comment by DaJMaN4** [comment] 2023-05-20 20:09
Thanks for help. I will just update the server to 1.19.4.
