### ISSUE TITLE
Biomes misbehaving

### ISSUE THREAD

**Issue by ArMiN231** [IrisDimensions/overworld#145] opened 2021-07-20 10:15 UTC
### Describe the problem

Broken oceans/islands
![ocean](https://user-images.githubusercontent.com/5337873/126307226-fe83c761-4670-4e4a-a400-3b7115a469b4.png)

### What Should Happen

Not Broken

### Minecraft Version

1.17.1

### Iris Version

1.5.4

### Checklist

- [X] I am using an unmodified version of the overworld. (If you modified the overworld and see an issue, contact [support](discord.gg/volmit))
- [X] I am using [the latest version of the overworld](../) **OR** I have made sure this issue was not already resolved on the latest version.
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by CocoTheOwner** [comment] 2021-07-20 10:16
```json

    "seaBiomes": [
        "tropical/tro-submerged-volcanic",
        "ocean/oce-tro-ocean",
        "tropical/tro-rainforest-island",
        "ocean/oce-tro-river-soft"
    ],
```
In the tropical region. This in combination with the minimal height of 25 for the islands is probably the cause.

**Comment by StrangeOne101** [comment] 2021-07-20 10:19
I think it's a Iris headless generation issue. I opened a studio world in 1.5.4 and found this:

![](https://cdn.discordapp.com/attachments/768582615078010910/866985938898124820/unknown.png)
Note the "Slope: 0". The slope just cuts to 0.

Yet generating the same world in 1.5.2 was absolutely fine.

**Comment by CocoTheOwner** [comment] 2021-07-20 10:20
No because these are chunks, I bet, while the issue above is not in straight lines, it's curved, like the biome itself.

**Comment by CocoTheOwner** [comment] 2021-07-20 10:20
Please open a different issue with that information on the plugin's issue tracker

**Comment by StrangeOne101** [comment] 2021-07-20 10:21
You're right, it's a biome issue. Found in 1.5.2 as well.

**Comment by CocoTheOwner** [comment] 2021-07-20 10:23
Brian fixed on overworld

**Closed by CocoTheOwner** 2021-07-20 10:23 UTC
